### ISSUE TITLE
missing Fair Trade links

### ISSUE THREAD

**Issue by dorothythompson** [culturalintrigue/bugtrack2015#12]
http://www.wfto.com
http://www.fairtradeforum.org

need to be added to icons on fair trade Tapestry products

**Comment by jamescultural** [comment]
added

**Comment by dorothythompson** [comment]
These tapestries are also Fair Trade.
I set them to 1 in IsFairTrade.
They still had icons in the Long Description, so I took that out.

Can you add *target="_blank"* to both icons in the box on the product page?



On Fri, Jan 23, 2015 at 12:17 PM, jamescultural <notifications@github.com>
wrote:

> added
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/culturalintrigue/bugtrack2015/issues/12#issuecomment-71228343>
> .
>



-- 
Dorothy Thompson
Online Marketing | Web Design
Cultural Intrigue
35 Frost St.
Brattleboro, VT 05301
802-246-2724
media@culturalintrigue.com
