### ISSUE TITLE
Zip Code - new issue - if 4-digit code is added -xxxx it won't show shipping

### ISSUE THREAD

**Issue by dorothythompson** [culturalintrigue/bugtrack2015#15]
Cult
Lenea had a customer that entered a Florida zip code xxxxx-xxxx.
When she looked at the Shipping method drop down, only "Use your own account" showed up, and she couldn't chose any shipping method. 

When the extra 4-digits were deleted, the shipping options showed up again.

**Comment by jamescultural** [comment]
I am going to try to see if I can use JavaScript to make the maximum characters for the zip code field 5

**Comment by dorothythompson** [comment]
What about Canadian postal codes?
I think they're more than 5 chars.
Does it currently work?

On Wed, Jan 28, 2015 at 4:35 PM, jamescultural <notifications@github.com>
wrote:

> I am going to try to see if I can use JavaScript to make the maximum
> characters for the zip code field 5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/culturalintrigue/bugtrack2015/issues/15#issuecomment-71921063>
> .
>



-- 
Dorothy Thompson
Online Marketing | Web Design
Cultural Intrigue
35 Frost St.
Brattleboro, VT 05301
802-246-2724
media@culturalintrigue.com

**Comment by jamescultural** [comment]
oh goosh, good thinking, they are 6,  im glad i didnt implement that

**Comment by jamescultural** [comment]
So I have set it to 6, using the code below in OnePageCheckout.js. I am closing this but if there are bugs we can reopen it!


> $('#addrBilling_txtZipCode').attr('maxlength', 6);
> $('#addrShipping_txtZipCode').attr('maxlength', 6);

**Comment by dorothythompson** [comment]
yay :)

but, we still don't have a solution to the problem.
have you ever spoken with a developer who is actually working on this code?
I wish I knew if they were changing it, or accidentally reverting to an
earlier version, or what?

On Wed, Jan 28, 2015 at 6:11 PM, jamescultural <notifications@github.com>
wrote:

> oh goosh, good thinking, they are 6, im glad i didnt implement that
>
> On Wed, Jan 28, 2015 at 2:56 PM, dorothythompson <notifications@github.com>
>
> wrote:
>
> > What about Canadian postal codes?
> > I think they're more than 5 chars.
> > Does it currently work?
> >
> > On Wed, Jan 28, 2015 at 4:35 PM, jamescultural <notifications@github.com>
>
> > wrote:
> >
> > > I am going to try to see if I can use JavaScript to make the maximum
> > > characters for the zip code field 5
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/culturalintrigue/bugtrack2015/issues/15#issuecomment-71921063>
>
> >
> > > .
> > >
> >
> >
> >
> > --
> > Dorothy Thompson
> > Online Marketing | Web Design
> > Cultural Intrigue
> > 35 Frost St.
> > Brattleboro, VT 05301
> > 802-246-2724
> > media@culturalintrigue.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/culturalintrigue/bugtrack2015/issues/15#issuecomment-71924957>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/culturalintrigue/bugtrack2015/issues/15#issuecomment-71936715>
> .
>



-- 
Dorothy Thompson
Online Marketing | Web Design
Cultural Intrigue
35 Frost St.
Brattleboro, VT 05301
802-246-2724
media@culturalintrigue.com
